### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by piranna** [kevva/decompress-tarxz#3]
I get the next error:

``` Javascript
TypeError: undefined is not a function
    at Ware.<anonymous> (/home/piranna/Proyectos/NodeOS/node_modules/download/node_modules/ware/node_modules/wrap-fn/index.js:75:16)
    at Ware.<anonymous> (/home/piranna/Proyectos/NodeOS/node_modules/download/node_modules/ware/node_modules/wrap-fn/index.js:57:27)
    at next (/home/piranna/Proyectos/NodeOS/node_modules/download/node_modules/ware/lib/index.js:85:20)
    at Ware.run (/home/piranna/Proyectos/NodeOS/node_modules/download/node_modules/ware/lib/index.js:88:3)
    at Download.<anonymous> (/home/piranna/Proyectos/NodeOS/node_modules/download/index.js:128:14)
    at emit (events.js:107:17)
    at EventEmitter.<anonymous> (/home/piranna/Proyectos/NodeOS/node_modules/got/index.js:170:9)
    at EventEmitter.emit (events.js:107:17)
    at ClientRequest.<anonymous> (/home/piranna/Proyectos/NodeOS/node_modules/got/index.js:50:7)
    at ClientRequest.g (events.js:199:16)
```

I've review the value of `fn` and in fact it's a stream:

``` Javascript
{ _readableState: 
   { highWaterMark: 16,
     buffer: [],
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: false,
     ended: false,
     endEmitted: false,
     reading: false,
     calledRead: false,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     objectMode: true,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events: 
   { end: { [Function: g] listener: [Function: onend] },
     finish: { [Function: g] listener: [Function] } },
  _maxListeners: undefined,
  _writableState: 
   { highWaterMark: 16,
     objectMode: true,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     decodeStrings: true,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function],
     writecb: null,
     writelen: 0,
     buffer: [],
     errorEmitted: false },
  writable: true,
  allowHalfOpen: true,
  _transformState: 
   { afterTransform: [Function],
     needTransform: false,
     transforming: false,
     writecb: null,
     writechunk: null },
  _destroyed: false,
  _transform: [Function] }
```

Maybe there's an incompatibility with newer versions of `download`?

**Comment by piranna** [comment]
Sorry, I confused Decompress and Download APIs. How can I be able to use decompress-tarxz with Download?

**Comment by mastilver** [comment]
@piranna I just made a PR to handle your usecase: https://github.com/kevva/download/pull/86
Feedback welcome ;)

**Comment by piranna** [comment]
Sorry, I changed my downloads to use `.tar.gz` on all of them... :-P But I've review your commits and seem good, the suggested API is clear :-)

**Comment by kevva** [comment]
You can supply your own `decompress` plugins by supplying the [`plugins`](https://github.com/kevva/decompress#plugins) option to `download` now.
